plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'java'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = 'raven-client-hud'
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:0.102.0+1.21.1"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	def mc = project.minecraft_version
	it.options.release = (mc.startsWith("1.21.") ? 21 : 25)
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

tasks.register('copyToLauncher', Copy) {
	dependsOn tasks.named('remapJar')
	from tasks.named('remapJar').flatMap { it.archiveFile }
	into file(rootProject.file('../src/main/resources'))
	rename { "raven-client-hud.jar" }
}
